name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.release_please_token }}
          release-type: simple
      - name: Enable Pull Request Auto-merge
        if: steps.release.outputs.prs_created && steps.release.outputs.pr != null
        run: gh pr merge --squash --auto ${{ fromJson(steps.release.outputs.pr).number }}
        env:
          GH_TOKEN: ${{ secrets.release_please_token }}
